services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: web_development_class
    ports:
      - 5432:5432

  student-management:
    image: student-management
    container_name: student-management
    build: .
    ports:
      - "8000:8080"